### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException in checkPenPosValidity

### ISSUE THREAD

**Issue by enzet** [bonnyfone/vectalign#7]
I am developing dynamic symbolic execution tool for Java programs. Now I am using it as fully automatic tool for defect detection on some open source programs from GitHub. It has found some `java.lang.ArrayIndexOutOfBoundsException`s in VectAlign:

```
java.lang.ArrayIndexOutOfBoundsException: -1
	at com.bonnyfone.vectalign.techniques.BaseFillMode.checkPenPosValidity(BaseFillMode.java:110)
	at com.bonnyfone.vectalign.techniques.BaseFillMode.fillInjectedNodes(BaseFillMode.java:101)
	at com.bonnyfone.vectalign.VectAlign.align(VectAlign.java:120)
	at com.bonnyfone.vectalign.Main.main(Main.java:104)
	at jia.test.big.VectalignTest.main(VectalignTest.java:23)
```

Constructed input was manually minimized to `-s L -e M`.

Arguments `to` and `from` (returned from method `doRawAlign`) of `fillInjectedNodes` method are empty `ArrayList`s. So I think either `doRawAlign` should not return empty lists or `checkPenPosValidity` should have additional check on its arguments.

Input is incorrect, so, please let me know is this a bug or undefined behavior caused by incorrect input. In other words, do you think analyzer has reported a real bug or a _false positive_.

**Comment by enzet** [comment]
Can I conclude that issue was a false positive?

**Comment by bonnyfone** [comment]
Closed as "won't fix" since it's and undefined behavior caused by incorrect input.
Thanks for reporting anyway.

**Comment by enzet** [comment]
Got it. Thanks for the answer.
